{% set name = "Orange3-Explain" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 57fd5b4b99ecc204b4ea4424f98ebdc63bd7dcf59ca2ff8e489c23939402ef51

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - Orange3
    - AnyQt
    - numpy
    - pyqtgraph
    - scipy
    - shap ==0.37.*

test:
  imports:
    - orangecontrib.explain

about:
  home: https://github.com/biolab/orange3-explain
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  summary: Explainable AI add-on for Orange3
  description: |
    Orange3 Explain is an add-on for the Orange3 data mining suite. 
    It provides extensions for explanatory AI.
  doc_url: http://orange3-explain.readthedocs.io/
  dev_url: https://github.com/biolab/orange3-explain

extra:
  recipe-maintainers:
    - PrimozGodec
